In [1]:
!pip install sqlalchemy psycopg2-binary
!pip install pyarrow

Requirement already satisfied: sqlalchemy in .\AppData\Roaming\Python\Python313\site-packages (2.0.49)
Requirement already satisfied: psycopg2-binary in .\anaconda3\Lib\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in .\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pyarrow in .\AppData\Roaming\Python\Python313\site-packages (20.0.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [4]:
import os

print(os.getcwd())

C:\Users\saite

In [6]:
file_path = r"D:\Aircraft-Maintenance-Analytics\data\processed9_cleaned.parquet"

print(os.path.exists(file_path))

True

In [7]:
df = pd.read_parquet(
    r"D:\Aircraft-Maintenance-Analytics\data\processed9_cleaned.parquet"
)

print(df.shape)
df.head()

(5918486, 34)

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,YEAR,MONTH,DAY,DAY_NAME,FLIGHT_STATUS,ON_TIME_FLAG,DELAY_CATEGORY
0,2009-01-01,XE,1204,DCA,EWR,1100,1058.0,-2.0,18.0,1116.0,...,0.0,0.0,0.0,2009,1,1,Thursday,On Time,1,On Time
1,2009-01-01,XE,1206,EWR,IAD,1510,1509.0,-1.0,28.0,1537.0,...,0.0,0.0,0.0,2009,1,1,Thursday,On Time,1,On Time
2,2009-01-01,XE,1207,EWR,DCA,1100,1059.0,-1.0,20.0,1119.0,...,0.0,0.0,0.0,2009,1,1,Thursday,On Time,1,On Time
3,2009-01-01,XE,1208,DCA,EWR,1240,1249.0,9.0,10.0,1259.0,...,0.0,0.0,0.0,2009,1,1,Thursday,On Time,1,On Time
4,2009-01-01,XE,1209,IAD,EWR,1715,1705.0,-10.0,24.0,1729.0,...,0.0,0.0,0.0,2009,1,1,Thursday,On Time,1,On Time

In [8]:
df.shape

(5918486, 34)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5918486 entries, 0 to 5918485
Data columns (total 34 columns):
 #   Column               Dtype
---  ------               -----
 0   FL_DATE              datetime64[ns]
 1   OP_CARRIER           object
 2   OP_CARRIER_FL_NUM    int32
 3   ORIGIN               object
 4   DEST                 object
 5   CRS_DEP_TIME         int32
 6   DEP_TIME             float32
 7   DEP_DELAY            float32
 8   TAXI_OUT             float32
 9   WHEELS_OFF           float32
 10  WHEELS_ON            float32
 11  TAXI_IN              float32
 12  CRS_ARR_TIME         int32
 13  ARR_TIME             float32
 14  ARR_DELAY            float32
 15  CANCELLED            float32
 16  CANCELLATION_CODE    object
 17  DIVERTED             float32
 18  CRS_ELAPSED_TIME     float32
 19  ACTUAL_ELAPSED_TIME  float32
 20  AIR_TIME             float32
 21  DISTANCE             float32
 22  CARRIER_DELAY        float32
 23  WEATHER_DELAY        float32
 24  NAS_DELAY            float32
 25  SECURITY_DELAY       float32
 26  LATE_AIRCRAFT_DELAY  float32
 27  YEAR                 int32
 28  MONTH                int32
 29  DAY                  int32
 30  DAY_NAME             object
 31  FLIGHT_STATUS        object
 32  ON_TIME_FLAG         int32
 33  DELAY_CATEGORY       object
dtypes: datetime64[ns](1), float32(19), int32(7), object(7)
memory usage: 948.2+ MB

In [10]:
df.describe()

,FL_DATE,OP_CARRIER_FL_NUM,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,...,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,YEAR,MONTH,DAY,ON_TIME_FLAG
count,5918486,5.918486e+06,5.918486e+06,5.838384e+06,5.838384e+06,5.835574e+06,5.835574e+06,5.832194e+06,5.832195e+06,5.918486e+06,...,5.918486e+06,5.918486e+06,5.918486e+06,5.918486e+06,5.918486e+06,5.918486e+06,5918486.0,5.918486e+06,5.918486e+06,5.918486e+06
mean,2009-06-21 09:40:19.990381824,2.288537e+03,1.320020e+03,1.326996e+03,7.928327e+00,1.609444e+01,1.351769e+03,1.478684e+03,6.896993e+00,1.497090e+03,...,7.255294e+02,2.868849e+00,5.207857e-01,3.089787e+00,1.216426e-02,3.680826e+00,2009.0,6.179537e+00,1.568326e+01,8.043596e-01
min,2009-01-01 00:00:00,1.000000e+00,1.000000e+00,1.000000e+00,-9.600000e+01,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,...,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2009.0,1.000000e+00,1.000000e+00,0.000000e+00
25%,2009-03-26 00:00:00,6.170000e+02,9.260000e+02,9.290000e+02,-5.000000e+00,1.000000e+01,9.440000e+02,1.107000e+03,4.000000e+00,1.119000e+03,...,3.250000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2009.0,3.000000e+00,8.000000e+00,1.000000e+00
50%,2009-06-17 00:00:00,1.626000e+03,1.315000e+03,1.323000e+03,-1.000000e+00,1.300000e+01,1.337000e+03,1.510000e+03,6.000000e+00,1.519000e+03,...,5.810000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2009.0,6.000000e+00,1.600000e+01,1.000000e+00
75%,2009-09-04 00:00:00,3.496000e+03,1.710000e+03,1.720000e+03,6.000000e+00,1.900000e+01,1.735000e+03,1.858000e+03,8.000000e+00,1.904000e+03,...,9.490000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2009.0,9.000000e+00,2.300000e+01,1.000000e+00
max,2009-12-31 00:00:00,7.829000e+03,2.359000e+03,2.400000e+03,2.445000e+03,4.580000e+02,2.400000e+03,2.400000e+03,1.970000e+02,2.400000e+03,...,4.962000e+03,2.439000e+03,1.114000e+03,1.305000e+03,3.450000e+02,1.391000e+03,2009.0,1.200000e+01,3.100000e+01,1.000000e+00
std,NaN,2.046443e+03,4.584292e+02,4.694415e+02,3.173237e+01,1.068049e+01,4.700362e+02,4.863175e+02,4.881154e+00,4.742222e+02,...,5.593690e+02,1.805810e+01,7.845958e+00,1.424988e+01,7.656377e-01,1.753635e+01,0.0,3.386869e+00,8.773362e+00,3.966929e-01

In [12]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

url = URL.create(
    drivername="postgresql+psycopg2",
    username="postgres",
    password="YOUR_PASSWORD",
    host="localhost",
    port=5432,
    database="aircraft_maintenance_db"
)

engine = create_engine(url)

with engine.connect() as conn:
    print("Database connection successful!")

Database connection successful!

In [13]:
print("Before connection")

with engine.connect() as conn:
    print("Database connection successful!")

print("After connection")

Before connection
Database connection successful!
After connection

In [14]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT version();"))
    
    for row in result:
        print(row[0])

PostgreSQL 18.4 on x86_64-windows, compiled by msvc-19.44.35226, 64-bit

In [15]:
df.head(1000).to_sql(
    "flight_operations",
    engine,
    if_exists="replace",
    index=False
)

print("1000 rows imported successfully!")

1000 rows imported successfully!

In [16]:
print(f"Memory Usage: {df.memory_usage(deep=True).sum()/1024**3:.2f} GB")

Memory Usage: 2.54 GB

In [18]:
df_sample = df.sample(n=500000, random_state=42)

print(df_sample.shape)

(500000, 34)

In [19]:
df_sample.to_sql(
    "flight_operations",
    engine,
    if_exists="replace",
    index=False,
    chunksize=50000,
    method="multi"
)

500000